APPBROWSER-298: Workaround Bifrost shader compiler issue
On Bifrost platform, we got this compile error for statement "data = unpack8_half(src_ptr[0])"
Error: Compiler log:
2:532: S0001: Function call discards 'readonly' access qualifier.

And we need to change it to "data = unpack8_half(uvec4(src_ptr[0]))"

Change-Id: I1b4cc66f88a57cf06275a74c796e89ed6043d2e5
Reviewed-on: http://mpd-gerrit.cambridge.arm.com/95773
Tested-by: Kaizen <jeremy.johnson+kaizengerrit@arm.com>
Reviewed-by: Stephen Li <stephen.li@arm.com>
(cherry picked from commit b2572a8de01cddc7adeacb2eed6a7ba7b8a6cc2d)
Reviewed-on: http://mpd-gerrit.cambridge.arm.com/95952
Reviewed-by: Anthony Barbier <anthony.barbier@arm.com>